using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QLabel.Scripts {
	internal static partial class ModelLabels {
		public static string[] coco80 = {
			  "person"
			 ,"bicycle"
			 ,"car"
			 ,"motorcycle"
			 ,"airplane"
			 ,"bus"
			 ,"train"
			 ,"truck"
			 ,"boat"
			 ,"traffic_light"
			 ,"fire_hydrant"
			 ,"stop_sign"
			 ,"parking_meter"
			 ,"bench"
			 ,"bird"
			 ,"cat"
			 ,"dog"
			 ,"horse"
			 ,"sheep"
			 ,"cow"
			 ,"elephant"
			 ,"bear"
			 ,"zebra"
			 ,"giraffe"
			 ,"backpack"
			 ,"umbrella"
			 ,"handbag"
			 ,"tie"
			 ,"suitcase"
			 ,"frisbee"
			 ,"skis"
			 ,"snowboard"
			 ,"sports_ball"
			 ,"kite"
			 ,"baseball_bat"
			 ,"baseball_glove"
			 ,"skateboard"
			 ,"surfboard"
			 ,"tennis_racket"
			 ,"bottle"
			 ,"wine_glass"
			 ,"cup"
			 ,"fork"
			 ,"knife"
			 ,"spoon"
			 ,"bowl"
			 ,"banana"
			 ,"apple"
			 ,"sandwich"
			 ,"orange"
			 ,"broccoli"
			 ,"carrot"
			 ,"hot_dog"
			 ,"pizza"
			 ,"donut"
			 ,"cake"
			 ,"chair"
			 ,"couch"
			 ,"potted_plant"
			 ,"bed"
			 ,"dining_table"
			 ,"toilet"
			 ,"tv"
			 ,"laptop"
			 ,"mouse"
			 ,"remote"
			 ,"keyboard"
			 ,"cell_phone"
			 ,"microwave"
			 ,"oven"
			 ,"toaster"
			 ,"sink"
			 ,"refrigerato"
			 ,"book"
			 ,"clock"
			 ,"vase"
			 ,"scissors"
			 ,"teddy_bea"
			 ,"hair_drier	"
			 ,"toothbrush"
		};
		public static string[] voc = new string[] { };
	}
}