using QLabel.Scripts.Projects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QLabel.Scripts {
	internal static partial class ModelLabels {
		public static ClassTemplate[] coco80 = {
		new ClassTemplate("Coco", "person", "person"),
		new ClassTemplate("Coco", "bicycle", "vehicle"),
		new ClassTemplate("Coco", "car", "vehicle"),
		new ClassTemplate("Coco", "motorcycle", "vehicle"),
		new ClassTemplate("Coco", "airplane", "vehicle"),
		new ClassTemplate("Coco", "bus", "vehicle"),
		new ClassTemplate("Coco", "train", "vehicle"),
		new ClassTemplate("Coco", "truck", "vehicle"),
		new ClassTemplate("Coco", "boat", "vehicle"),
		new ClassTemplate("Coco", "traffic light", "outdoor"),
		new ClassTemplate("Coco", "fire_hydrant", "outdoor"),
		new ClassTemplate("Coco", "stop_sign", "outdoor"),
		new ClassTemplate("Coco", "parking_meter", "outdoor"),
		new ClassTemplate("Coco", "bench", "outdoor"),
		new ClassTemplate("Coco", "bird", "animal"),
		new ClassTemplate("Coco", "cat", "animal"),
		new ClassTemplate("Coco", "dog", "animal"),
		new ClassTemplate("Coco", "horse", "animal"),
		new ClassTemplate("Coco", "sheep", "animal"),
		new ClassTemplate("Coco", "cow", "animal"),
		new ClassTemplate("Coco", "elephant", "animal"),
		new ClassTemplate("Coco", "bear", "animal"),
		new ClassTemplate("Coco", "zebra", "animal"),
		new ClassTemplate("Coco", "giraffe", "animal"),
		new ClassTemplate("Coco", "backpack", "accessory"),
		new ClassTemplate("Coco", "umbrella", "accessory"),
		new ClassTemplate("Coco", "handbag", "accessory"),
		new ClassTemplate("Coco", "tie", "accessory"),
		new ClassTemplate("Coco", "suitcase", "accessory"),
		new ClassTemplate("Coco", "frisbee", "sports"),
		new ClassTemplate("Coco", "skis", "sports"),
		new ClassTemplate("Coco", "snowboard", "sports"),
		new ClassTemplate("Coco", "sports_ball", "sports"),
		new ClassTemplate("Coco", "kite", "sports"),
		new ClassTemplate("Coco", "baseball_bat", "sports"),
		new ClassTemplate("Coco", "baseball_glove", "sports"),
		new ClassTemplate("Coco", "skateboard", "sports"),
		new ClassTemplate("Coco", "surfboard", "sports"),
		new ClassTemplate("Coco", "tennis_racket", "sports"),
		new ClassTemplate("Coco", "bottle", "kitchen"),
		new ClassTemplate("Coco", "wine_glass", "kitchen"),
		new ClassTemplate("Coco", "cup", "kitchen"),
		new ClassTemplate("Coco", "fork", "kitchen"),
		new ClassTemplate("Coco", "knife", "kitchen"),
		new ClassTemplate("Coco", "spoon", "kitchen"),
		new ClassTemplate("Coco", "bowl", "kitchen"),
		new ClassTemplate("Coco", "banana", "food"),
		new ClassTemplate("Coco", "apple", "food"),
		new ClassTemplate("Coco", "sandwich", "food"),
		new ClassTemplate("Coco", "orange", "food"),
		new ClassTemplate("Coco", "broccoli", "food"),
		new ClassTemplate("Coco", "carrot", "food"),
		new ClassTemplate("Coco", "hot_dog", "food"),
		new ClassTemplate("Coco", "pizza", "food"),
		new ClassTemplate("Coco", "donut", "food"),
		new ClassTemplate("Coco", "cake", "food"),
		new ClassTemplate("Coco", "chair", "food"),
		new ClassTemplate("Coco", "couch", "furniture"),
		new ClassTemplate("Coco", "potted plant", "furniture"),
		new ClassTemplate("Coco", "bed", "furniture"),
		new ClassTemplate("Coco", "dining table", "furniture"),
		new ClassTemplate("Coco", "toilet", "furniture"),
		new ClassTemplate("Coco", "tv", "electronic"),
		new ClassTemplate("Coco", "laptop", "electronic"),
		new ClassTemplate("Coco", "mouse", "electronic"),
		new ClassTemplate("Coco", "remote", "electronic"),
		new ClassTemplate("Coco", "keyboard", "electronic"),
		new ClassTemplate("Coco", "cell phone", "electronic"),
		new ClassTemplate("Coco", "microwave", "appliance"),
		new ClassTemplate("Coco", "oven", "appliance"),
		new ClassTemplate("Coco", "toaster", "appliance"),
		new ClassTemplate("Coco", "sink", "appliance"),
		new ClassTemplate("Coco", "refrigerato", "appliance"),
		new ClassTemplate("Coco", "book", "indoor"),
		new ClassTemplate("Coco", "clock", "indoor"),
		new ClassTemplate("Coco", "vase", "indoor"),
		new ClassTemplate("Coco", "scissors", "indoor"),
		new ClassTemplate("Coco", "teddy bea", "indoor"),
		new ClassTemplate("Coco", "hair drier", "indoor"),
		new ClassTemplate("Coco", "toothbrush", "indoor")};
	}
}
