using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QLabel.Scripts {
	internal static partial class ModelLabels {
		public static ClassLabel[] coco80 = {
		new ClassLabel("Coco", "person"),
		new ClassLabel("Coco", "bicycle"),
		new ClassLabel("Coco", "car"),
		new ClassLabel("Coco", "motorcycle"),
		new ClassLabel("Coco", "airplane"),
		new ClassLabel("Coco", "bus"),
		new ClassLabel("Coco", "train"),
		new ClassLabel("Coco", "truck"),
		new ClassLabel("Coco", "boat"),
		new ClassLabel("Coco", "traffic_light"),
		new ClassLabel("Coco", "fire_hydrant"),
		new ClassLabel("Coco", "stop_sign"),
		new ClassLabel("Coco", "parking_meter"),
		new ClassLabel("Coco", "bench"),
		new ClassLabel("Coco", "bird"),
		new ClassLabel("Coco", "cat"),
		new ClassLabel("Coco", "dog"),
		new ClassLabel("Coco", "horse"),
		new ClassLabel("Coco", "sheep"),
		new ClassLabel("Coco", "cow"),
		new ClassLabel("Coco", "elephant"),
		new ClassLabel("Coco", "bear"),
		new ClassLabel("Coco", "zebra"),
		new ClassLabel("Coco", "giraffe"),
		new ClassLabel("Coco", "backpack"),
		new ClassLabel("Coco", "umbrella"),
		new ClassLabel("Coco", "handbag"),
		new ClassLabel("Coco", "tie"),
		new ClassLabel("Coco", "suitcase"),
		new ClassLabel("Coco", "frisbee"),
		new ClassLabel("Coco", "skis"),
		new ClassLabel("Coco", "snowboard"),
		new ClassLabel("Coco", "sports_ball"),
		new ClassLabel("Coco", "kite"),
		new ClassLabel("Coco", "baseball_bat"),
		new ClassLabel("Coco", "baseball_glove"),
		new ClassLabel("Coco", "skateboard"),
		new ClassLabel("Coco", "surfboard"),
		new ClassLabel("Coco", "tennis_racket"),
		new ClassLabel("Coco", "bottle"),
		new ClassLabel("Coco", "wine_glass"),
		new ClassLabel("Coco", "cup"),
		new ClassLabel("Coco", "fork"),
		new ClassLabel("Coco", "knife"),
		new ClassLabel("Coco", "spoon"),
		new ClassLabel("Coco", "bowl"),
		new ClassLabel("Coco", "banana"),
		new ClassLabel("Coco", "apple"),
		new ClassLabel("Coco", "sandwich"),
		new ClassLabel("Coco", "orange"),
		new ClassLabel("Coco", "broccoli"),
		new ClassLabel("Coco", "carrot"),
		new ClassLabel("Coco", "hot_dog"),
		new ClassLabel("Coco", "pizza"),
		new ClassLabel("Coco", "donut"),
		new ClassLabel("Coco", "cake"),
		new ClassLabel("Coco", "chair"),
		new ClassLabel("Coco", "couch"),
		new ClassLabel("Coco", "potted_plant"),
		new ClassLabel("Coco", "bed"),
		new ClassLabel("Coco", "dining_table"),
		new ClassLabel("Coco", "toilet"),
		new ClassLabel("Coco", "tv"),
		new ClassLabel("Coco", "laptop"),
		new ClassLabel("Coco", "mouse"),
		new ClassLabel("Coco", "remote"),
		new ClassLabel("Coco", "keyboard"),
		new ClassLabel("Coco", "cell_phone"),
		new ClassLabel("Coco", "microwave"),
		new ClassLabel("Coco", "oven"),
		new ClassLabel("Coco", "toaster"),
		new ClassLabel("Coco", "sink"),
		new ClassLabel("Coco", "refrigerato"),
		new ClassLabel("Coco", "book"),
		new ClassLabel("Coco", "clock"),
		new ClassLabel("Coco", "vase"),
		new ClassLabel("Coco", "scissors"),
		new ClassLabel("Coco", "teddy_bea"),
		new ClassLabel("Coco", "hair_drier"),
		new ClassLabel("Coco", "toothbrush")
				};
	}
}
