using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QLabel.Scripts {
	internal static partial class ModelLabels {
		public static ClassLabel[] coco80 = {
		new ClassLabel("Coco", "person", "person"),
		new ClassLabel("Coco", "bicycle", "vehicle"),
		new ClassLabel("Coco", "car", "vehicle"),
		new ClassLabel("Coco", "motorcycle", "vehicle"),
		new ClassLabel("Coco", "airplane", "vehicle"),
		new ClassLabel("Coco", "bus", "vehicle"),
		new ClassLabel("Coco", "train", "vehicle"),
		new ClassLabel("Coco", "truck", "vehicle"),
		new ClassLabel("Coco", "boat", "vehicle"),
		new ClassLabel("Coco", "traffic light", "outdoor"),
		new ClassLabel("Coco", "fire_hydrant", "outdoor"),
		new ClassLabel("Coco", "stop_sign", "outdoor"),
		new ClassLabel("Coco", "parking_meter", "outdoor"),
		new ClassLabel("Coco", "bench", "outdoor"),
		new ClassLabel("Coco", "bird", "animal"),
		new ClassLabel("Coco", "cat", "animal"),
		new ClassLabel("Coco", "dog", "animal"),
		new ClassLabel("Coco", "horse", "animal"),
		new ClassLabel("Coco", "sheep", "animal"),
		new ClassLabel("Coco", "cow", "animal"),
		new ClassLabel("Coco", "elephant", "animal"),
		new ClassLabel("Coco", "bear", "animal"),
		new ClassLabel("Coco", "zebra", "animal"),
		new ClassLabel("Coco", "giraffe", "animal"),
		new ClassLabel("Coco", "backpack", "accessory"),
		new ClassLabel("Coco", "umbrella", "accessory"),
		new ClassLabel("Coco", "handbag", "accessory"),
		new ClassLabel("Coco", "tie", "accessory"),
		new ClassLabel("Coco", "suitcase", "accessory"),
		new ClassLabel("Coco", "frisbee", "sports"),
		new ClassLabel("Coco", "skis", "sports"),
		new ClassLabel("Coco", "snowboard", "sports"),
		new ClassLabel("Coco", "sports_ball", "sports"),
		new ClassLabel("Coco", "kite", "sports"),
		new ClassLabel("Coco", "baseball_bat", "sports"),
		new ClassLabel("Coco", "baseball_glove", "sports"),
		new ClassLabel("Coco", "skateboard", "sports"),
		new ClassLabel("Coco", "surfboard", "sports"),
		new ClassLabel("Coco", "tennis_racket", "sports"),
		new ClassLabel("Coco", "bottle", "kitchen"),
		new ClassLabel("Coco", "wine_glass", "kitchen"),
		new ClassLabel("Coco", "cup", "kitchen"),
		new ClassLabel("Coco", "fork", "kitchen"),
		new ClassLabel("Coco", "knife", "kitchen"),
		new ClassLabel("Coco", "spoon", "kitchen"),
		new ClassLabel("Coco", "bowl", "kitchen"),
		new ClassLabel("Coco", "banana", "food"),
		new ClassLabel("Coco", "apple", "food"),
		new ClassLabel("Coco", "sandwich", "food"),
		new ClassLabel("Coco", "orange", "food"),
		new ClassLabel("Coco", "broccoli", "food"),
		new ClassLabel("Coco", "carrot", "food"),
		new ClassLabel("Coco", "hot_dog", "food"),
		new ClassLabel("Coco", "pizza", "food"),
		new ClassLabel("Coco", "donut", "food"),
		new ClassLabel("Coco", "cake", "food"),
		new ClassLabel("Coco", "chair", "food"),
		new ClassLabel("Coco", "couch", "furniture"),
		new ClassLabel("Coco", "potted plant", "furniture"),
		new ClassLabel("Coco", "bed", "furniture"),
		new ClassLabel("Coco", "dining table", "furniture"),
		new ClassLabel("Coco", "toilet", "furniture"),
		new ClassLabel("Coco", "tv", "electronic"),
		new ClassLabel("Coco", "laptop", "electronic"),
		new ClassLabel("Coco", "mouse", "electronic"),
		new ClassLabel("Coco", "remote", "electronic"),
		new ClassLabel("Coco", "keyboard", "electronic"),
		new ClassLabel("Coco", "cell phone", "electronic"),
		new ClassLabel("Coco", "microwave", "appliance"),
		new ClassLabel("Coco", "oven", "appliance"),
		new ClassLabel("Coco", "toaster", "appliance"),
		new ClassLabel("Coco", "sink", "appliance"),
		new ClassLabel("Coco", "refrigerato", "appliance"),
		new ClassLabel("Coco", "book", "indoor"),
		new ClassLabel("Coco", "clock", "indoor"),
		new ClassLabel("Coco", "vase", "indoor"),
		new ClassLabel("Coco", "scissors", "indoor"),
		new ClassLabel("Coco", "teddy bea", "indoor"),
		new ClassLabel("Coco", "hair drier", "indoor"),
		new ClassLabel("Coco", "toothbrush", "indoor")};
	}
}
